name: Build
on:
  pull_request:
  push:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pre-build
        run: scripts/update_package_json_version.sh
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
